### PR TITLE
added EULA setup

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ocxo** [comment]
I don't recall having any trouble installing the vmware module via boxen. What does this solve?

**Comment by techtribe** [comment]
when you install you need to agree the Extended User License Agreement and therefore I thought to use the appdmg_eula setup. So no problems solved, but I assumed a step less needed, right?

**Comment by ocxo** [comment]
That makes sense but I don't recall seeing this. I just removed Fusion from my machine and re-ran boxen and also did not get an EULA prompt.

**Comment by joeyvandijk** [comment]
Ok, fine, I thought I saw it and implemented it, but if you checked it then ignore this PR.

**Comment by ocxo** [comment]
Thanks, going to close this one out for now.

**Pull request closed without merging**
